name: iot-testing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytest>=7.0
  - pytest-cov>=4.0
  - pytest-xdist>=3.0
  - pytest-mock>=3.0
  - pytest-benchmark>=4.0
  - pytest-html>=3.0
  - coverage>=7.0
  - black>=22.0
  - flake8>=5.0
  - mypy>=1.0
  - boto3>=1.26.0
  - botocore>=1.29.0
  - requests>=2.28.0
  - pydantic>=1.10.0
  - pip:
    - aws-cdk-lib>=2.80.0
    - constructs>=10.1.0
    - moto[all]>=4.1.0
    - pytest-asyncio>=0.21.0
    - pytest-timeout>=2.1.0
    - pytest-env>=0.8.0
    - faker>=18.0.0
    - python-dotenv>=1.0.0
    - httpx>=0.24.0
    - asyncio-mqtt>=0.13.0
    - psutil>=5.9.0 